// research-gateway/react-frontend/src/components/NotFound/NotFound.tsx
import { Button, Result } from 'antd';
import { Link } from 'react-router-dom';
import { constants } from '../../constants/constants';

const NotFound = () => {
    return (
        <>
            <Result
                status="404"
                title="404"
                subTitle="Sorry, the page you visited does not exist."
                extra={(
                    <Button
                        type="primary"
                    >
                        <Link to={constants.ROUTING.HOME}>Back Home</Link>
                    </Button>
                )}
            />
        </>
    );
};

export default NotFound;

// pure-vuejs/todo-vue/src/components/NotFound.vue
<script setup lang="ts">
</script>

<template>
    <a-result status="404" title="404" sub-title="Sorry, the page you looking for is not exist!">
        <template #extra>
            <a-button type="primary">
                <RouterLink to="/">Go to Home</RouterLink>
            </a-button>
        </template>
    </a-result>
</template>

<style scoped></style>
